In [1]:
import numpy as np
np.__version__

'1.21.5'

In [2]:
import numpy as np
list1 = [10,20,30,40]
array1 = np.array([10,20,30,40])
list1+2 # not possible

TypeError: can only concatenate list (not "int") to list

In [3]:
import numpy as np
array1 = np.array([10,20,30,40])
array1+2 # array([12,22,32,42])

array([12, 22, 32, 42])

In [4]:
import numpy as np
import sys
l = [10,20,30,40,50,60,70,80,90,100,10,20,30,40,50,60,70,80,90,100]
a = np.array([10,20,30,40,50,60,70,80,90,100,10,20,30,40,50,60,70,80,90,100])
print('The Size of list l => ',sys.getsizeof(l))
print('The Size of ndarray a => ',sys.getsizeof(a))

The Size of list l =>  216
The Size of ndarray a =>  184


In [5]:
import numpy as np
from datetime import datetime
a = np.array([10,20,30])
b = np.array([1,2,3])
#dot product: A.B=10X1 + 20X2 +30X3=140
#traditional python code
def dot_product(a,b):
 result = 0
 for i,j in zip(a,b):
     result = result + i*j
 return result
before = datetime.now()
for i in range(1000000):
 dot_product(a,b)
after = datetime.now()
print('The Time taken by traditonal python:',after-before)
#numpy library code
before = datetime.now()
for i in range(1000000):
 np.dot(a,b) # this is from numpy
after = datetime.now()
print('The Time taken by Numpy Library:',after-before)

The Time taken by traditonal python: 0:00:05.848978
The Time taken by Numpy Library: 0:00:04.618354


In [6]:
import numpy as np
import time
import sys
SIZE =1000000
l1 = range(SIZE)
l2 = range(SIZE)
a1 = np.arange(SIZE)
a2 = np.arange(SIZE)
#python list
start = time.time()
result = [ (x+y) for x,y in zip(l1,l2)]
# adds first element in l1 with first element of l2 and so on
print("Pyton list took : ",(time.time() - start)*1000)
#numpy array
start= time.time()
result = a1 + a2
print("Numpy array took : ",(time.time() - start)*1000)

Pyton list took :  312.9448890686035
Numpy array took :  33.87904167175293


In [7]:
import array
a = array.array('i',[10,20,30]) # i represents int type array
print(f"Type of a ==> {type(a)}") # array.array
print(f"a value ==> {a}")
print("Elements one by one")
for x in range(len(a)):
    print(a[x])


Type of a ==> <class 'array.array'>
a value ==> array('i', [10, 20, 30])
Elements one by one
10
20
30


In [8]:
import numpy as np
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

In [9]:
# 1-D array creation from list or tuple
l = [10,20,30]
print(f'Type of l ==> {type(l)}')
a = np.array(l)
print(f'Type of a ==> {type(a)}')
print(f"a ==> {a}")


Type of l ==> <class 'list'>
Type of a ==> <class 'numpy.ndarray'>
a ==> [10 20 30]


In [10]:
# properties of ndarray
print(f'The dimensions of the array a ==> {a.ndim}')
print(f'The data type of elements of array a ==> {a.dtype}')
print(f'The size of the array a ==> {a.size}')
print(f'The shape of the array a ==> {a.shape}')

The dimensions of the array a ==> 1
The data type of elements of array a ==> int32
The size of the array a ==> 3
The shape of the array a ==> (3,)


In [11]:
# 1-D array creating using tuples
t = ('krishna','nandu','moneesh')
print(f'Type of t ==> {type(t)}')
a = np.array(t)
print(f'Type of a ==> {type(a)}')
print(f'The data type of elements of array a ==> {a.dtype}')
print(f'The size of the array a ==> {a.size}')
print(f'The shape of the array a ==> {a.shape}')
print(f"a ==> {a}")


Type of t ==> <class 'tuple'>
Type of a ==> <class 'numpy.ndarray'>
The data type of elements of array a ==> <U7
The size of the array a ==> 3
The shape of the array a ==> (3,)
a ==> ['krishna' 'nandu' 'moneesh']


In [12]:
# [[10,20,30],[40,50,60],[70,80,90]] --->Nested List
a = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(f'Type of a ==> {type(a)}')
print(f'a ==> \n {a}')
print(f'The dimensions of the array a ==> {a.ndim}')
print(f'The data type of elements of array a ==> {a.dtype}')
print(f'The size of the array a ==> {a.size}')
print(f'The shape of the array a ==> {a.shape}')

Type of a ==> <class 'numpy.ndarray'>
a ==> 
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
The dimensions of the array a ==> 2
The data type of elements of array a ==> int32
The size of the array a ==> 9
The shape of the array a ==> (3, 3)


In [13]:
# list contains heterogenous elements
l = [10,20,30.5]
a = np.array(l) # upcasting to float
print(f'a :: {a}')
print(f'data type of elements of a ==> {a.dtype}')

a :: [10.  20.  30.5]
data type of elements of a ==> float64


In [14]:
# int type
a = np.array([10,20,30.5],dtype=int)
print(a)

[10 20 30]


In [15]:
# float type
a = np.array([10,20,30.5],dtype=float)
print(a)

[10.  20.  30.5]


In [16]:
# bool type ==> any number is True and zero is False. Any string is True and empty string is False
a = np.array([10,20,30.5],dtype=bool)
print(a)

[ True  True  True]


In [17]:
# complex type
a = np.array([10,20,30.5,0],dtype=complex)
print(a)

[10. +0.j 20. +0.j 30.5+0.j  0. +0.j]


In [18]:
# str type
a = np.array([10,20,30.5],dtype=str)
print(a)

['10' '20' '30.5']


In [19]:
a = np.array([10,'krishna',10.5,True,10+20j],dtype=object)
print(a)
# data type
print(f"Data type of elements of array a ==> {a.dtype}")

[10 'krishna' 10.5 True (10+20j)]
Data type of elements of array a ==> object


In [20]:
import numpy as np
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off 

In [21]:
# only stop value ==> 0 to stop-1
import numpy as np
a = np.arange(10)
print(f'a ==> {a}')
print(f'The dimensions of the array a ==> {a.ndim}')
print(f'The data type of elements of array a ==> {a.dtype}')
print(f'The size of the array a ==> {a.size}')
print(f'The shape of the array a ==> {a.shape}')

a ==> [0 1 2 3 4 5 6 7 8 9]
The dimensions of the array a ==> 1
The data type of elements of array a ==> int32
The size of the array a ==> 10
The shape of the array a ==> (10,)


In [22]:
# both start and stop values: start to stop-1
import numpy as np
a = np.arange(1,11)
print(f'a ==> {a}')
print(f'The dimensions of the array a ==> {a.ndim}')
print(f'The data type of elements of array a ==> {a.dtype}')
print(f'The size of the array a ==> {a.size}')
print(f'The shape of the array a ==> {a.shape}')

a ==> [ 1  2  3  4  5  6  7  8  9 10]
The dimensions of the array a ==> 1
The data type of elements of array a ==> int32
The size of the array a ==> 10
The shape of the array a ==> (10,)


In [23]:
# start, stop and step values : start to stop-1 with step
import numpy as np
a = np.arange(1,11,2)
print(f'a ==> {a}')
print(f'The dimensions of the array a ==> {a.ndim}')
print(f'The data type of elements of array a ==> {a.dtype}')
print(f'The size of the array a ==> {a.size}')
print(f'The shape of the array a ==> {a.shape}')

a ==> [1 3 5 7 9]
The dimensions of the array a ==> 1
The data type of elements of array a ==> int32
The size of the array a ==> 5
The shape of the array a ==> (5,)


In [24]:
# with a particular datatype of the elements
import numpy as np
a = np.arange(1,11,3,dtype=float)
print(f'a ==> {a}')
print(f'The dimensions of the array a ==> {a.ndim}')
print(f'The data type of elements of array a ==> {a.dtype}')
print(f'The size of the array a ==> {a.size}')
print(f'The shape of the array a ==> {a.shape}')

a ==> [ 1.  4.  7. 10.]
The dimensions of the array a ==> 1
The data type of elements of array a ==> float64
The size of the array a ==> 4
The shape of the array a ==> (4,)


In [25]:
import numpy as np
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [26]:
# 50 evenly spaced values between 0 and 1 are returned including both 0 and 1
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [27]:
# 4 evenly spaced valued between 0 and 1 including 0 and 1
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [28]:
# 4 evenly spaced valued between 0 and 1 including 0 and excluding 1
np.linspace(0,1,4,endpoint=False)

array([0.  , 0.25, 0.5 , 0.75])